@baseUrl = http://192.168.4.1

### Read the current ear LED state
GET {{baseUrl}}/ears

### Set ear brightness percentage
PUT {{baseUrl}}/ears
Content-Type: application/x-www-form-urlencoded

brightnessPercent=35

### Set ear brightness using the raw 0-255 scale
PUT {{baseUrl}}/ears
Content-Type: application/x-www-form-urlencoded

brightness=15
