@baseUrl = http://192.168.4.1

### List uploaded animation files
GET {{baseUrl}}/files

### Get data partition usage info
GET {{baseUrl}}/files-info

### Upload a test animation file
# @name uploadTestAnimation
POST {{baseUrl}}/file
Content-Type: multipart/form-data; boundary=ProtogenBoundary

--ProtogenBoundary
Content-Disposition: form-data; name="file"; filename="rest-test-upload.txt"
Content-Type: text/plain

This is a test upload created from test/http-files/Files.http.
--ProtogenBoundary--

### Get file content 
GET {{baseUrl}}/file?file=/anims/rest-test-upload.txt

### Delete the uploaded test animation file
DELETE {{baseUrl}}/file?file=/anims/rest-test-upload.txt
